<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>49b93767-2f20-4e4d-8800-1d9b77565894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'validar2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#validar2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='validar2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validar2</value>
      <webElementGuid>e7bcb686-b442-4129-a04e-850718ba4135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20f58d9f-b43e-4927-abfa-be89db81e544</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validar2']</value>
      <webElementGuid>a4aed224-5b49-4266-a3e2-85db83bbae27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>44f87ba5-9baf-4a98-8ec0-2f1709eba392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'validar2' and @id = 'validar2']</value>
      <webElementGuid>261b0ede-8210-42f8-8219-194e504bfb8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
