<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_logout</name>
   <tag></tag>
   <elementGuidId>718f7a02-a6e2-4d95-a94d-d1789718c907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>i[title='Salir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>i[title='Salir']</value>
      <webElementGuid>299aefb1-ca7a-49e6-9811-a0cef0d23084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c9ff5e5-875e-48c5-b248-312b63f8256c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
