<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_usuario</name>
   <tag></tag>
   <elementGuidId>f710438f-3216-4c90-b2fd-eee65e4f1707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textfield</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield</value>
      <webElementGuid>23e664fd-b9c2-4e95-b434-f7026813a2ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield']</value>
      <webElementGuid>05dc0519-453c-448d-8dd0-723fe1398e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58d4b1e1-6f4a-4772-b5aa-418d81c27e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtuser' and @id = 'textfield']</value>
      <webElementGuid>43cb112f-fa50-4a15-8fd4-21a64700f790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
