<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Auditoria</name>
   <tag></tag>
   <elementGuidId>b1e7ca7f-1927-41c1-9760-4b6b9f6dc47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cmMenu450']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>740b01ea-6be0-402b-b048-5604c14627ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmMenu450</value>
      <webElementGuid>c26921e2-02a5-45dd-9c7f-b2e619c302c1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
