<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_NuevaAuditoria</name>
   <tag></tag>
   <elementGuidId>62179fa1-f00d-479b-b86b-8ae1441ecc9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cmMenu471']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7f12d6a-9eef-4034-905d-b4f1676a108a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmMenu471</value>
      <webElementGuid>d186494a-a99c-4d84-b1fb-afda98028da2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
