<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdmProgram</name>
   <tag></tag>
   <elementGuidId>79806a90-fe3f-4aae-8c0c-110f5d63ffcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cmMenu411']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmMenu411</value>
      <webElementGuid>ec95754e-10c3-418b-ac22-64a7202abc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>616c50ae-d03e-47ca-9b73-824a36bfd8a5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
